Repository 5tarlight/Jasao, pull requests merged in 2023-08, with the labels that each got.

#48 Image upload
  .gitignore
  cdn/.gitignore
  cdn/index.js
  cdn/package.json
  cdn/yarn.lock
  jasao-frontend/src/App.tsx
  jasao-frontend/src/pages/test.tsx
  jasao-frontend/src/styles/Test.module.scss
  jasao-server/src/main/kotlin/io/yeahx4/jasao/controller/UserController.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/entity/user/User.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/service/user/UserService.kt
Labels: size/XL

#50 header dropdown
  jasao-frontend/.gitignore
  jasao-frontend/package.json
  jasao-frontend/public/index.html
  jasao-frontend/src/components/header/HeaderDropdown.tsx
  jasao-frontend/src/components/header/HeaderDropdownItem.tsx
  jasao-frontend/src/components/header/LoginHeader.tsx
  jasao-frontend/src/styles/header/Header.module.scss
  jasao-frontend/src/util/server.ts
  jasao-frontend/yarn.lock
  jasao-server/src/main/kotlin/io/yeahx4/jasao/SecurityConfig.kt
Labels: size/L

#54 Profile image
  jasao-frontend/src/components/header/HeaderDropdown.tsx
  jasao-frontend/src/pages/test.tsx
  jasao-server/src/main/kotlin/io/yeahx4/jasao/SecurityConfig.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/controller/file/UploadedFileController.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/controller/user/UserController.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/dto/user/UserDto.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/entity/file/UploadedFile.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/entity/user/User.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/repository/file/UploadedFileRepository.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/role/file/FileExtension.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/role/file/UploadedFileRole.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/role/user/UserRole.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/service/file/UploadedFileService.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/service/user/UserService.kt
Labels: size/L

#55 Extract configuration and secrets into properties
  jasao-server/.gitignore
  jasao-server/src/main/kotlin/io/yeahx4/jasao/JasaoServerApplication.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/jwt/JwtTokenProvider.kt
  jasao-server/src/main/resources/application.properties
  jasao-server/src/main/resources/jasao.properties.template
Labels: size/S

#56 Auth Input validation
  jasao-frontend/src/pages/auth/Login.tsx
  jasao-frontend/src/pages/auth/SignUp.tsx
  jasao-frontend/src/util/auth.ts
  jasao-server/src/main/kotlin/io/yeahx4/jasao/util/isEmail.kt
Labels: size/M

#57 Show profile image instead of username
  cdn/index.js
  jasao-frontend/public/person.svg
  jasao-frontend/src/components/ProfileImage.tsx
  jasao-frontend/src/components/header/Header.tsx
  jasao-frontend/src/components/header/LoginHeader.tsx
  jasao-frontend/src/pages/auth/Login.tsx
  jasao-frontend/src/styles/ProfileImage.module.scss
  jasao-frontend/src/styles/header/Header.module.scss
  jasao-frontend/src/util/server.ts
Labels: size/L

#58 Jasao 1.0.1
  .gitignore
  cdn/.gitignore
  cdn/index.js
  cdn/package.json
  cdn/yarn.lock
  jasao-frontend/.gitignore
  jasao-frontend/package.json
  jasao-frontend/public/index.html
  jasao-frontend/public/person.svg
  jasao-frontend/src/App.tsx
  jasao-frontend/src/components/ProfileImage.tsx
  jasao-frontend/src/components/header/Header.tsx
  jasao-frontend/src/components/header/HeaderDropdown.tsx
  jasao-frontend/src/components/header/HeaderDropdownItem.tsx
  jasao-frontend/src/components/header/LoginHeader.tsx
  jasao-frontend/src/pages/auth/Login.tsx
  jasao-frontend/src/pages/auth/SignUp.tsx
  jasao-frontend/src/pages/test.tsx
  jasao-frontend/src/styles/ProfileImage.module.scss
  jasao-frontend/src/styles/Test.module.scss
  jasao-frontend/src/styles/header/Header.module.scss
  jasao-frontend/src/util/auth.ts
  jasao-frontend/src/util/server.ts
  jasao-frontend/src/util/storage.ts
  jasao-frontend/yarn.lock
  jasao-server/.gitignore
  jasao-server/build.gradle.kts
  jasao-server/src/main/kotlin/io/yeahx4/jasao/JasaoServerApplication.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/SecurityConfig.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/controller/file/UploadedFileController.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/controller/user/UserController.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/dto/user/UserDto.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/entity/file/UploadedFile.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/entity/user/User.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/jwt/JwtTokenProvider.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/repository/file/UploadedFileRepository.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/role/file/FileExtension.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/role/file/UploadedFileRole.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/role/user/UserRole.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/service/file/UploadedFileService.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/util/isEmail.kt
  jasao-server/src/main/resources/application.properties
  jasao-server/src/main/resources/jasao.properties.template
Labels: size/XXL

#63 Follow user
  jasao-server/src/main/kotlin/io/yeahx4/jasao/SecurityConfig.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/controller/user/UserCommunityController.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/controller/user/UserController.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/dto/user/UserCommunityDto.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/dto/user/UserDto.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/entity/user/Following.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/entity/user/User.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/repository/user/FollowingRepository.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/service/user/FollowingService.kt
Labels: size/L, backend

#64 Profile page
  jasao-frontend/src/App.tsx
  jasao-frontend/src/components/EditableText.tsx
  jasao-frontend/src/components/ProfileImage.tsx
  jasao-frontend/src/components/header/HeaderDropdown.tsx
  jasao-frontend/src/components/popup/Input.tsx
  jasao-frontend/src/components/profile/UserInformation.tsx
  jasao-frontend/src/pages/profile/ViewProfile.tsx
  jasao-frontend/src/styles/Constant.scss
  jasao-frontend/src/styles/EditableText.module.scss
  jasao-frontend/src/styles/popup/Input.module.scss
  jasao-frontend/src/styles/profile/Profile.module.scss
  jasao-frontend/src/util/utilities.ts
  jasao-frontend/yarn.lock
Labels: size/XXL

#66 Apply page for following and followed list
  jasao-server/src/main/kotlin/io/yeahx4/jasao/controller/user/UserCommunityController.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/dto/user/UserCommunityDto.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/entity/user/Following.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/repository/user/FollowingRepository.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/service/user/FollowingService.kt
Labels: size/M, backend

#68 Profile page - follow
  jasao-frontend/src/App.tsx
  jasao-frontend/src/components/EditableText.tsx
  jasao-frontend/src/components/popup/Input.tsx
  jasao-frontend/src/components/popup/Popup.tsx
  jasao-frontend/src/components/profile/UserInformation.tsx
  jasao-frontend/src/pages/popupTest.tsx
  jasao-frontend/src/pages/profile/ViewProfile.tsx
  jasao-frontend/src/styles/EditableText.module.scss
  jasao-frontend/src/styles/popup/Popup.module.scss
  jasao-frontend/src/util/auth.ts
  jasao-frontend/src/util/server.ts
  jasao-frontend/src/util/user.ts
  jasao-frontend/src/util/utilities.ts
Labels: size/XL

#70 Add follow response details
  jasao-server/src/main/kotlin/io/yeahx4/jasao/controller/user/UserCommunityController.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/dto/user/UserCommunityDto.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/repository/user/FollowingRepository.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/service/user/FollowingService.kt
Labels: size/M

#73 remove token field
  jasao-frontend/src/util/server.ts
  jasao-frontend/src/util/storage.ts
Labels: size/XS

#75 Check i'm following
  jasao-frontend/src/components/popup/Popup.tsx
  jasao-frontend/src/components/profile/FollowList.tsx
  jasao-frontend/src/components/profile/UserInfo.tsx
  jasao-frontend/src/styles/popup/Popup.module.scss
  jasao-frontend/src/util/server.ts
Labels: size/M

#76 Upload profile image / Edit bio
  jasao-frontend/src/components/EditableText.tsx
  jasao-frontend/src/components/popup/Popup.tsx
  jasao-frontend/src/components/popup/UploadFile.tsx
  jasao-frontend/src/components/profile/UserInfo.tsx
  jasao-frontend/src/pages/popupTest.tsx
  jasao-frontend/src/pages/test.tsx
  jasao-frontend/src/styles/EditableText.module.scss
  jasao-frontend/src/styles/popup/Popup.module.scss
  jasao-frontend/src/styles/profile/Profile.module.scss
  jasao-frontend/src/util/auth.ts
  jasao-frontend/src/util/utilities.ts
Labels: size/XL

#80 bug fix: bio is not refreshed
  jasao-frontend/src/components/profile/UserInfo.tsx
Labels: size/XS

#81 Change password
  jasao-frontend/src/App.tsx
  jasao-frontend/src/components/popup/ChangePasswordPopup.tsx
  jasao-frontend/src/components/popup/Input.tsx
  jasao-frontend/src/components/popup/InputPopup.tsx
  jasao-frontend/src/components/popup/Popup.tsx
  jasao-frontend/src/components/popup/UploadFile.tsx
  jasao-frontend/src/components/popup/UploadFilePopup.tsx
  jasao-frontend/src/components/profile/UserInfo.tsx
  jasao-frontend/src/pages/newPopupTest.tsx
  jasao-frontend/src/pages/popupTest.tsx
  jasao-frontend/src/styles/popup/Popup.module.scss
Labels: size/XXL

#82 Bug fix: Profile image preview
  jasao-frontend/src/components/profile/UserInfo.tsx
Labels: size/XS

#84 Remove profile image backend API
  jasao-server/src/main/kotlin/io/yeahx4/jasao/controller/file/UploadedFileController.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/controller/user/UserController.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/service/file/UploadedFileService.kt
Labels: size/M, backend

#83 Remove Profile Image frontend
  jasao-frontend/src/components/popup/UploadFilePopup.tsx
  jasao-frontend/src/components/profile/UserInfo.tsx
  jasao-frontend/src/pages/user/ViewProfile.tsx
  jasao-frontend/src/styles/popup/Popup.module.scss
Labels: size/L

#85 Block backend API
  jasao-server/src/main/kotlin/io/yeahx4/jasao/controller/user/UserCommunityController.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/dto/user/BlockDto.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/entity/user/UserBlock.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/repository/user/UserBlockRepository.kt
  jasao-server/src/main/kotlin/io/yeahx4/jasao/service/user/BlockUserService.kt
Labels: size/M, backend

#86 Block/Unblock User
  jasao-frontend/src/components/profile/UserInfo.tsx
  jasao-server/src/main/kotlin/io/yeahx4/jasao/controller/user/UserCommunityController.kt
Labels: size/M

#89 Create backend_test.yml
  .github/workflows/backend.yml
  jasao-server/src/test/kotlin/io/yeahx4/jasao/JasaoServerApplicationTests.kt
Labels: size/M
